# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.downloadButton = QtWidgets.QPushButton(self.tab)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_3.addWidget(self.downloadButton, 2, 1, 1, 1)
        self.syncButton = QtWidgets.QPushButton(self.tab)
        self.syncButton.setObjectName("syncButton")
        self.gridLayout_3.addWidget(self.syncButton, 2, 0, 1, 1)
        self.treeItems = QtWidgets.QTreeWidget(self.tab)
        self.treeItems.setObjectName("treeItems")
        self.treeItems.header().setDefaultSectionSize(400)
        self.treeItems.header().setMinimumSectionSize(400)
        self.gridLayout_3.addWidget(self.treeItems, 1, 0, 1, 2)
        self.dummyButton = QtWidgets.QPushButton(self.tab)
        self.dummyButton.setObjectName("dummyButton")
        self.gridLayout_3.addWidget(self.dummyButton, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.colorLegendButton = QtWidgets.QPushButton(self.tab)
        self.colorLegendButton.setObjectName("colorLegendButton")
        self.horizontalLayout_8.addWidget(self.colorLegendButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 496))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 11, 1, 1, 1)
        self.checkBox_show_events = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_show_events.setObjectName("checkBox_show_events")
        self.gridLayout.addWidget(self.checkBox_show_events, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 16, 1, 1, 1)
        self.checkBox_overwrite_existing_files = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_overwrite_existing_files.setObjectName("checkBox_overwrite_existing_files")
        self.gridLayout.addWidget(self.checkBox_overwrite_existing_files, 17, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 19, 1, 1, 1)
        self.checkBox_all_semesters = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_all_semesters.setObjectName("checkBox_all_semesters")
        self.gridLayout.addWidget(self.checkBox_all_semesters, 2, 1, 1, 1)
        self.checkBox_course_as_folder = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_course_as_folder.setObjectName("checkBox_course_as_folder")
        self.gridLayout.addWidget(self.checkBox_course_as_folder, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.checkBox_semester_as_folder = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_semester_as_folder.setObjectName("checkBox_semester_as_folder")
        self.gridLayout.addWidget(self.checkBox_semester_as_folder, 6, 1, 1, 1)
        self.checkBox_lecturer_as_folder = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_lecturer_as_folder.setObjectName("checkBox_lecturer_as_folder")
        self.gridLayout.addWidget(self.checkBox_lecturer_as_folder, 10, 1, 1, 1)
        self.radioButton_semester_naming_v2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_semester_naming_v2.setObjectName("radioButton_semester_naming_v2")
        self.gridLayout.addWidget(self.radioButton_semester_naming_v2, 14, 1, 1, 1)
        self.radioButton_semester_naming_v1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_semester_naming_v1.setObjectName("radioButton_semester_naming_v1")
        self.gridLayout.addWidget(self.radioButton_semester_naming_v1, 13, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 12, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 15, 1, 1, 1)
        self.checkBox_enable_loggin = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_enable_loggin.setObjectName("checkBox_enable_loggin")
        self.gridLayout.addWidget(self.checkBox_enable_loggin, 20, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.selectDirectoryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectDirectoryButton.setObjectName("selectDirectoryButton")
        self.gridLayout.addWidget(self.selectDirectoryButton, 0, 2, 1, 1)
        self.directoryPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.directoryPath.setObjectName("directoryPath")
        self.gridLayout.addWidget(self.directoryPath, 0, 1, 1, 1)
        self.directoryPathLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.directoryPathLabel.setObjectName("directoryPathLabel")
        self.gridLayout.addWidget(self.directoryPathLabel, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 18, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OC-Sync"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.syncButton.setText(_translate("MainWindow", "Synchronisieren"))
        self.treeItems.headerItem().setText(0, _translate("MainWindow", "Information"))
        self.treeItems.headerItem().setText(1, _translate("MainWindow", "Dateiname"))
        self.treeItems.headerItem().setText(2, _translate("MainWindow", "Download Url"))
        self.treeItems.headerItem().setText(3, _translate("MainWindow", "Dateipfad"))
        self.treeItems.headerItem().setText(4, _translate("MainWindow", "Upload Datum"))
        self.dummyButton.setText(_translate("MainWindow", "Dummy Button"))
        self.colorLegendButton.setText(_translate("MainWindow", "Farbcode Informationen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dateien"))
        self.label_4.setText(_translate("MainWindow", "Allgemein"))
        self.checkBox_show_events.setText(_translate("MainWindow", "Kurstermine in der Übersicht anzeigen"))
        self.label_6.setText(_translate("MainWindow", "Download"))
        self.checkBox_overwrite_existing_files.setText(_translate("MainWindow", "Vorhandene Dateien überschreiben"))
        self.label_5.setText(_translate("MainWindow", "Logging"))
        self.checkBox_all_semesters.setText(_translate("MainWindow", "Alle Semester synchronisieren"))
        self.checkBox_course_as_folder.setText(_translate("MainWindow", "Ordner für jeden Kurs anlegen"))
        self.checkBox_semester_as_folder.setText(_translate("MainWindow", "Ordner für jedes Semester anlegen"))
        self.checkBox_lecturer_as_folder.setText(_translate("MainWindow", "Ordner für jeden Dozenten anlegen. Kann bei Kursen mit zwei Dozenten hilfreich sein."))
        self.radioButton_semester_naming_v2.setText(_translate("MainWindow", "Benennung: 1. Semester, 2. Semester, etc."))
        self.radioButton_semester_naming_v1.setText(_translate("MainWindow", "Benennung: WS 19, SS 19, etc."))
        self.label_2.setText(_translate("MainWindow", "Ordnerbenennung Semester"))
        self.checkBox_enable_loggin.setText(_translate("MainWindow", "Logging aktivieren"))
        self.label.setText(_translate("MainWindow", "Optionen"))
        self.label_3.setText(_translate("MainWindow", "Ordnerstruktur beim Download"))
        self.selectDirectoryButton.setText(_translate("MainWindow", "Auswählen"))
        self.directoryPathLabel.setText(_translate("MainWindow", "Download Ordner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Einstellungen"))


